sudo: false
language: java
jdk:
  - oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_toolboxPluginVersion=${TOOLBOX_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_twigPluginVersion=${TWIG_PLUGIN_VERSION}"

env:
  - IDEA_VERSION="IU-2018.1" PHP_PLUGIN_VERSION="181.4203.565" TOOLBOX_PLUGIN_VERSION="0.4.6" TWIG_PLUGIN_VERSION="181.3741.23"
  - IDEA_VERSION="IU-2017.3.5" PHP_PLUGIN_VERSION="173.4301.34" TOOLBOX_PLUGIN_VERSION="0.4.6" TWIG_PLUGIN_VERSION="173.4301.7"

script:
- "./gradlew check buildPlugin"
