<?php

namespace {{namespace}};

use Doctrine\ORM\EntityRepository;

/**
 * {{class}}
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class {{class}} extends EntityRepository
{
}
